name: tapoviewer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-164.0.dev

dependencies:
  flutter:
    sdk: flutter
  media_kit: ^1.1.11
  media_kit_libs_video: ^1.0.5
  media_kit_video: ^1.2.5
  network_info_plus: ^7.0.0
  network_tools: ^5.0.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
